name: Manual Version Bump to Next SNAPSHOT

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch for the PR (default: main)'
        required: false
        default: 'main'

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Calculate next snapshot version
        id: bump
        run: |
          current_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Current version: $current_version"
          base_version=$(echo $current_version | sed 's/-.*//')
          IFS='.' read -r major minor patch <<< "$base_version"
          next_patch=$((patch + 1))
          next_version="${major}.${minor}.${next_patch}-SNAPSHOT"
          echo "Next version: $next_version"
          echo "next_version=$next_version" >> $GITHUB_OUTPUT

      - name: Create new branch
        run: |
          git checkout -b bump-version-${{ steps.bump.outputs.next_version }}

      - name: Bump version and commit
        run: |
          mvn versions:set -DnewVersion=${{ steps.bump.outputs.next_version }}
          mvn versions:commit

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "chore: bump version to ${{ steps.bump.outputs.next_version }}"

      - name: Push changes to new branch
        run: |
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-version-${{ steps.bump.outputs.next_version }}
          base: ${{ github.event.inputs.base_branch }}
          title: "chore: bump version to ${{ steps.bump.outputs.next_version }}"
          body: |
            This PR updates the project version to `${{ steps.bump.outputs.next_version }}`.
