ALTER SESSION SET CONTAINER=FREEPDB1;
GRANT SELECT ON sys.dba_pending_transactions TO "TEST";
GRANT SELECT ON sys.pending_trans$ TO "TEST";
GRANT SELECT ON sys.dba_2pc_pending TO "TEST";
GRANT EXECUTE ON sys.dbms_xa TO "TEST";
GRANT FORCE ANY TRANSACTION TO "TEST";
-- Workaround for ORA-08177 occurring on isolation level TRANSACTION_SERIALIZABLE
ALTER SYSTEM SET DEFERRED_SEGMENT_CREATION=false;
